### PR TITLE
Build OpenMM-Torch 1.2

### PR DESCRIPTION
**Pull request by raimis**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by raimis** [comment]
@conda-forge-admin, please rerender

**Comment by raimis** [comment]
@mikemhenry have you any idea why the AArch64 builds are failing?

**Comment by mikemhenry** [comment]
I will investigate :thinking: 

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/opt/conda/lib/python3.10/site-packages/boa/core/solver.py", line 244, in solve_for_action
    t = self.solve(specs)
  File "/opt/conda/lib/python3.10/site-packages/boa/core/solver.py", line 234, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - python
 - openmm >=8.0.0
 - python 3.9.* *_cpython
 - pytorch 2.0.*
 - pytorch * cuda*
 - pytorch
 - swig <4.1
 - ocl-icd
 - pip

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested pytorch * cuda*
- 
```

Since they did work, I am guessing that things changed slightly to break something in the processing of the recipe. It might be related to the cuda 12 migration stuff, so I will check there first.

**Comment by mikemhenry** [comment]
@raimis I've fixed the builds :sunglasses:

**Comment by raimis** [comment]
@mikemhenry thank you for your effort!

**Pull request merged**
