### PR TITLE
Feat/add pytorch 1.11 and 1.12

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@peastman this doubles our build matrix but I think this is what we need to have pytorch 1.11 and 1.12. Let's see if it builds how we expect!

**Comment by peastman** [comment]
The PyTorch 1.11 builds fail, because it's trying to install both 1.11 and 1.12 at the same time.  The generated yaml files for those builds specify

```
pytorch:
- '1.12'
pytorch_version:
- 1.11.0
```

I'm not sure where it's getting that from.

**Comment by jaimergp** [comment]
`pytorch` is part of [the global pinnings](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/de38483b220ed1c027f38a0d9aae8d6adde8a3e2/recipe/conda_build_config.yaml#L627-L628), so ideally that's the one all feedstocks build against.

If both versions must be built no matter what, then the key to override in conda_build_config.yaml is `pytorch`, not `pytorch_version`, and undo the changes in meta.yaml (leave the glob).

> The comments in meta.yaml [hinted](https://github.com/conda-forge/openmm-torch-feedstock/pull/27/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR47-R48) at this perhaps too subtly!

**Comment by jaimergp** [comment]
Alternatively, leave the conda_build_config.yaml as is and edit meta.yaml so the version pin applies to the (now bare) `pytorch` line, not the one with the glob expression. 

Please note this manual override will disregard global pinnings, possibly leaving this feedstock behind in terms of support for new pytorch versions.

**Comment by mikemhenry** [comment]
@jaimergp thanks so much! I think I did it correctly (per your first comment). I'd like to follow the global pining, but I think TorchMD-Net https://github.com/openmm/openmm/issues/3610#issuecomment-1256568921 doesn't support 1.11 yet.

**Comment by jaimergp** [comment]
The py38/arm64 error is a segfault coming from pylief. I've seen this in other feedstocks and retrying usually works. Keep that in mind for the eventual merge to `main` (make sure it's all green once it lands!).

Also a reminder you are now in pytorch manual mode and I am not sure if the bot will issue rebuilds for new pytorch releases once the pin changes globally. Keep a look on the conda-forge-pinning` feedstock!

**Comment by mikemhenry** [comment]
@peastman this should be good to merge, it targets the `rc` label.

**Review by peastman — APPROVED** [review]
Looks good.

**Pull request merged**
