### PR TITLE
Update Swig Pin

### PR DESCRIPTION
**Pull request by mikemhenry**
- pin swig to not pull in new version that break things
- MNT: Re-rendered with conda-build 3.21.8, conda-smithy 3.21.2, and conda-forge-pinning 2022.10.25.15.13.01

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peastman** [comment]
Looks good.

**Comment by raimis** [comment]
Some wrong is going on with the Mac build:
```
The reported errors are:
- Encountered problems while solving:
-   - package openmm-7.5.0-py36h2b32750_5_apple requires python_abi 3.6.* *_cp36m, but none of the providers can be installed
```

**Comment by mikemhenry** [comment]
@raimis @peastman 

I belive that is a consequence of not having python 3.10 mac os builds for openmm. So that just means if we merge this, people will not be able to install this package on on mac os with python 3.10, but will with python 3.7, 3.8, and 3.9

**Comment by peastman** [comment]
That problem should be fixed once we release OpenMM 8.0.  It will include Python 3.10 (and hopefully also 3.11) builds.

**Comment by raimis** [comment]
Pinning Swig (https://github.com/openmm/openmm-torch/pull/86) is just a temporary solution. It looks like some syntax error in  `include/swig/OpenMMSwigHeaders.i`. So ideally, the header should be updated (if possible), so can keep using the latest Swig and don't get stuck with old versions.

**Comment by mikemhenry** [comment]
@peastman So are we good to merge this? That way at least users installing this package will get the correct version of swig

**Comment by peastman** [comment]
Ok.

**Pull request closed without merging**
