### PR TITLE
Rmove run_constrained

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
But I wanted to make sure I change one thing at a time

**Comment by peastman** [comment]
I don't think you removed the `run_constrained`?

Shall we try also adding a pytorch 1.13 build?

**Comment by mikemhenry** [comment]
@peastman you are right, I just re-rendered it and forgot to commit the changes. And yah, might as well give that a shot as well

**Comment by peastman** [comment]
All the builds are failing.  I think it needs to have swig pinned.

**Comment by peastman** [comment]
I pinned the swig version.  Let's see if it works now.

**Comment by mikemhenry** [comment]
@peastman so far so good...

**Comment by mikemhenry** [comment]
@peastman do we want to test this or should I just turn on auto merge?

**Comment by mikemhenry** [comment]
@peastman looks good! I will now update the env files

**Comment by peastman** [comment]
We also need to enable pytorch 1.13 builds.

**Comment by mikemhenry** [comment]
Will do! I will get those going on another PR since at least now we can have people test if removing `run_constrained` works

**Pull request merged**
