### PR TITLE
Rebuild for openmm 8.0.0rc1

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
I also added in python 3.11 into this re-build to see if we get anything new

**Comment by mikemhenry** [comment]
@peastman @hmacdope

This is the rebuild for the new openmm rc. I changed the recipe to point to the new rc + added the python 3.11 migration. We might need to rebuild some other packages to get this to work. I'll get PRs open for all the downstream openmm packages and we can see where the CI dust settles.

**Comment by peastman** [comment]
A bunch of builds are failing:

```
Mamba failed to solve:
 - python
 - openmm 8.0.0beta
 - ocl-icd
 - pip
 - python 3.11.* *_cpython
 - pytorch 1.11.0.*
 - swig <4.1
 - pytorch
 - pytorch * cuda*

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package openmm-8.0.0beta-py310h2996cf7_2 requires python_abi 3.10.* *_cp310, but none of the providers can be installed
```

It's trying to install the Python 3.10 build of OpenMM with Python 3.11.

**Comment by peastman** [comment]
It also was trying to install the OpenMM beta rather than the rc.

**Comment by peastman** [comment]
I think the problem is this line in the `host:` section:

```yaml
    - openmm ==8.0.0beta
```

**Comment by mikemhenry** [comment]
Good catch!

**Comment by mikemhenry** [comment]
I think I should also change the version to match the rc version of openmm

**Comment by mikemhenry** [comment]
I will go through why these are failing, a really quick check seems to indicate some issues with trying to support a lot of cuda, python versions, and pytorch versions which may be incompatible, so we will need to mark those builds to skip

**Comment by peastman** [comment]
I think there are two different problems.  When we merged the PR to build the OpenMM release candidate, [one build failed](https://github.com/conda-forge/openmm-feedstock/runs/10571245770) with a timeout.  It's the one for Linux with Python 3.10 and CUDA 11.1.  That causes the builds here for that combination to fail.  Hopefully all we need to do is rerun it.

Other builds are failing due to unsupported combinations.  For example, the Linux Python 3.11, CUDA 11.2, PyTorch 1.11 build reports this error:

> conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("python_abi=3.7[build=*_cp37m]"), MatchSpec("pytorch==1.11.0=cuda102py37hb1831c0_0")}

It appears that PyTorch 1.11 only has builds for Python 3.7 through 3.10.

**Comment by peastman** [comment]
I reran the OpenMM builds and it worked this time.  The one missing package is now up, so those failures should be fixed.

**Comment by peastman** [comment]
All but one of the builds succeeded.  That remaining one seems to be stuck printing out the message "is not an ELF" thousands of times???

**Comment by mikemhenry** [comment]
@peastman I've seen that happen on OSX builds sometimes, normally it eventually stops, then works. I am inclined to merge this since when I have seen that issue before, it tends to go away when you re-run the build

**Comment by peastman** [comment]
One build failure with an error I haven't seen before:

```
Setting up cross-python
find: fts_read: Invalid argument
```

I'll try rerunning it and see what happens.

**Comment by mikemhenry** [comment]
Looks like we are all good now!
https://github.com/conda-forge/openmm-torch-feedstock/commits/rc

**Pull request merged**
