### PR TITLE
Update to 0.5

### PR DESCRIPTION
**Pull request by raimis**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by raimis** [comment]
@conda-forge-admin, please rerender

**Comment by raimis** [comment]
Solves https://github.com/openmm/openmm-torch/issues/54

**Comment by raimis** [comment]
@peastman @jaimergp this is ready!

**Review by jaimergp — APPROVED** [review]
LGTM! And wow we have a lot of builds! :D

**Comment by raimis** [comment]
I don't have the permission to merge. So, I will apply to become a maintainer.

**Comment by raimis** [comment]
https://github.com/conda-forge/openmm-torch-feedstock/pull/14

**Pull request merged**
